name: Publish to Pub.dev

on:
  release:
    types: [published]
    
jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Publish
        uses: k-paxian/dart-package-publisher@v1.3